# Generated by Django 3.2.9 on 2021-11-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('tag', models.CharField(blank=True, max_length=20)),
                ('complete_yn', models.BooleanField()),
                ('complete_date', models.DateTimeField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
