# Generated by Django 3.2.9 on 2021-11-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
